### ISSUE TITLE
Add union based APIs

### ISSUE THREAD

**Issue by jvliwanag** [purescript-aws-sdk/purescript-aws-request#37]
Instead of encoding all options with all fields filled up with a default `Nothing` value, accept instead partial record opts via Unions.

This would allow service creation such as:

```purescript
service name { maxRetries: 5, accessKeyId: "foo" }
```

instead of

```purescript
service name (defaultOptions' (_ { maxRetries = 5, accessKeyId = "foo } ) )
```

**Comment by plippe** [comment]
I didn't know you could do this with unions. 
Great improvement to the API.
