### ISSUE TITLE
Change `service` to be pure

### ISSUE THREAD

**Issue by jvliwanag** [purescript-aws-sdk/purescript-aws-request#39]
Right now, the service creation API is declared to be `Effect`ful. 

Since we don't really offer any way to modify the resulting `Service`, then creating a Service is actually pure.

Can we then change the service creation API type signature?

`service :: ServiceName -> Options -> Effect Service` 

to 

`service :: ServiceName -> Options -> Service`

**Comment by plippe** [comment]
I always assumed creating the service could failed when certain criterias weren't met, _missing credentials_, _missing region_, ...

If this is true, it might be worth keeping `Effect Service`, otherwise `Service` makes more sense.

**Comment by jvliwanag** [comment]
Missing credentials, missing region etc fail when the api call is executed, not when the service is created.

That said, browsed through the aws-sdk-js code, and one mutable feature we might want later on is adding request listeners. This would then need service creation to be effectful for us to get some reference to which we can add listeners to.

So closing this.
